### PR TITLE
Fix 1.4 bugs for exam

### LINKED ISSUE #189: [PE-D][Tester B] Wrong exam deleted when 2 exams have the same details
## Steps to reproduce

1. Create an exam for student 1 (smaller ID).

2. Create an exam for student 2 (larger ID) with the exact same exam details.

3. Try to delete the exam for student 2.

## Expected result

The exam for student 2 is deleted.

## Actual result

The exam for student 1 is deleted.

<i><video controls><source src="https://raw.githubusercontent.com/chaaaaun/ped/main/files/48cb677e-1264-4d1f-8742-59f846f668cb.mov" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/chaaaaun/ped/main/files/48cb677e-1264-4d1f-8742-59f846f668cb.mov</i>

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: chaaaaun/ped#23

### PR DESCRIPTION
**Pull request by jessicawyz**
1. Fix duplicate exams
2. Fix exams unable to delete
3. Fix silent failures error messages in exam

closes #189, #164, #159, #157, #152

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddExamCommandParser.java [hunk 1]
```diff
@@ -27,13 +28,13 @@ public AddExamCommand parse(String args) throws ParseException {
...
-        assert argMultimap.getValue(PREFIX_ID).isPresent() : "Prefix ID value is missing";
-        assert argMultimap.getValue(PREFIX_EXAM_NAME).isPresent() : "Prefix Exam Name value is missing";
-        assert argMultimap.getValue(PREFIX_DATE).isPresent() : "Prefix Date value is missing";
 
         String uniqueId = argMultimap.getValue(PREFIX_ID).get();
         String examName = ParserUtil.parseExamName(argMultimap.getValue(PREFIX_EXAM_NAME).get());
         LocalDate date = ParserUtil.parseDate(argMultimap.getValue(PREFIX_DATE).get());
+        if (date.isBefore(LocalDate.now())) {
+            throw new ParseException(MESSAGE_CONSTRAINTS_PAST_DATE);
+        }
```
Comment (KinTatHo) [inline src/main/java/seedu/address/logic/parser/AddExamCommandParser.java:37]: am i able to still add exams on the same day but at a past timing?

File: src/main/java/seedu/address/model/person/Exam.java [hunk 2]
```diff
@@ -82,9 +83,16 @@ public static boolean isValidExamName(String name) {
     /**
      * Returns true if a given date is a valid exam date (from today onwards).
      */
-    public static boolean isValidExamDate(LocalDate test) {
+    public static boolean isValidExamDate(LocalDate test) throws IllegalArgumentException {
         LocalDate currentDate = LocalDate.now();
-        return !test.isBefore(currentDate);
+        try {
```
Comment (KinTatHo) [inline src/main/java/seedu/address/model/person/Exam.java:88]: i think checking whether test time is before current time is good too

**Review by KinTatHo — CHANGES_REQUESTED** [review]
LGTM, but do the exams disappear when its over?

File: src/main/java/seedu/address/logic/parser/AddExamCommandParser.java (hunk 1 above)
Comment (MarcusGitty) [reply src/main/java/seedu/address/logic/parser/AddExamCommandParser.java:37]: Yes, we are still able to add a exam date that is on the same day but is at a past timing, 

Adding exams past the current date will throw the correct error message though

File: src/main/java/seedu/address/model/person/Exam.java (hunk 2 above)
Comment (MarcusGitty) [reply src/main/java/seedu/address/model/person/Exam.java:88]: Yaa i think it'll be good, but this can't be done, it'll be considered a feature flaw

**Review by MarcusGitty — APPROVED** [review]
LGTM, there are stuff that we would like to fix but can't due to the feature freeze limitations

**Review by MarcusGitty — CHANGES_REQUESTED** [review]
I found a new bug, if i add exams inside that is valid, for example today, 8/4/2024, and i open TuteeTally tmr, I can't

as the exams stored will be deemed invalid as shown below.

From investigating, this bug is present in our v1.3.1

image

File: src/main/java/seedu/address/logic/Messages.java [hunk 3]
```diff
@@ -21,6 +21,9 @@ public class Messages {
                 "Multiple values specified for the following single-valued field(s): ";
     public static final String MESSAGE_PERSON_NOT_FOUND = "Person not found";
     public static final String MESSAGE_EXAM_NOT_FOUND = "Exam to delete cannot be found";
+    public static final String MESSAGE_EXAM_ALREADY_EXIST =
+            "Exam cannot be added because exam to be added already exists";
+    public static final String MESSAGE_CONSTRAINTS_PAST_DATE = "Exam date in the past is invalid.";
```
[the remark this answers is not in the document]
Comment (jessicawyz) [reply src/main/java/seedu/address/logic/Messages.java:26]: This one is fine because no error message existed before feature freeze and it was a silent failure problem. I can make it more specific

**Comment by jessicawyz** [comment]
> I found a new bug, if i add exams inside that is valid, for example today, 8/4/2024, and i open TuteeTally tmr, I can't
> 
> as the exams stored will be deemed invalid as shown below.
> 
> From investigating, this bug is present in our v1.3.1
> 
> image

I have fixed this bug by adding a check when data is loaded from storage. If date is in the past we will remove the exam from the person and the allExamsList so exams in the past are no displayed and will not cause the addressbook to crash. However this data is only updated to json file for storage when user inputs "exit". Please help to check if this is a reasonable fix and does not introduce new bugs.

**Comment by MarcusGitty** [comment]
This seems to fix the issue

File: src/main/java/seedu/address/storage/JsonAdaptedPerson.java [hunk 4]
```diff
@@ -107,9 +107,14 @@ public Person toModelType() throws IllegalValueException {
...
         }
 
+
         final List<Exam> personExams = new ArrayList<>();
         for (JsonAdaptedExam exam : exams) {
-            personExams.add(exam.toModelType());
+            if (!exam.isExamOverdue(exam)) {
+                personExams.add(exam.toModelType());
+            } else {
+                System.out.println("removed past exams: " + exam);
```
Comment (KinTatHo) [inline src/main/java/seedu/address/storage/JsonAdaptedPerson.java:116]: nice changes, but i think can remove print statements

**Review by KinTatHo — APPROVED** [review]

File: src/main/java/seedu/address/storage/JsonAdaptedPerson.java (hunk 4 above)
Comment (jessicawyz) [reply src/main/java/seedu/address/storage/JsonAdaptedPerson.java:116]: I added for us to keep track of the process. ok will remove
