### PR TITLE
Bugfix v1.2 From 83 Failing Test Case reduced to 9

### LINKED ISSUE #51: What to do with Failing Test Cases
image

Currently we're failing 83/267 automated test cases from "./gradlew clean  test", this causes us to fail the github CI tracking. 

Maybe in the next iteration we can focus more on making test cases for our code.

### PR DESCRIPTION
**Pull request by MarcusGitty**
Fix #51, #57, #59, #58

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java [hunk 1]
```diff
@@ -36,6 +36,10 @@ public class CommandTestUtil {
     public static final String VALID_ADDRESS_BOB = "Block 123, Bobby Street 3";
     public static final String VALID_TAG_HUSBAND = "husband";
     public static final String VALID_TAG_FRIEND = "friend";
+    public static final String VALID_SUBJECT_AMY = "Math";
+    public static final String VALID_SUBJECT_BOB = "English";
+    public static final String VALID_ID_AMY = "10";
+    public static final String VALID_ID_BOB = "11";
```
Comment (MarcusGitty) [inline src/test/java/seedu/address/logic/commands/CommandTestUtil.java:42]: On hindsight there shouldn't be an ID

**Review by KinTatHo — APPROVED** [review]
LGTM, nice job Marcus
