### PR TITLE
Fix add command tests and style errors

### LINKED ISSUE #55: Add Command 4 Tests Failing in AddCommandIntegrationTest.java AddCommandTest.java
Currently the Add Command Feature have 4 test failing in these 2 test classes

AddCommandIntegrationTest.java 
AddCommandTest.java 

image

### PR DESCRIPTION
**Pull request by 0nesheep**
closes #55

### CODE REVIEW

File: src/test/java/seedu/address/testutil/TypicalPersons.java [hunk 1]
```diff
@@ -138,7 +138,7 @@ public class TypicalPersons {
     private TypicalPersons() {} // prevents instantiation
 
     private static String getNextUniqueId() {
-        return String.format("#%06d", uniqueIdCounter++);
+        return String.format("%06d", uniqueIdCounter++);
```
Comment (MarcusGitty) [inline src/test/java/seedu/address/testutil/TypicalPersons.java:141]: I suspect this is why JsonAddressBookStorageTest > readAndSaveAddressBook_allInOrder_success() FAILED

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java [hunk 2]
```diff
@@ -167,7 +167,9 @@ public int getTotalPersons() {
 
         @Override
         public String getNextUniqueId() {
-            throw new AssertionError("This method should not be called.");
+            // Function needs to be called in order to generate new person model
+            /*throw new AssertionError("This method should not be called.");*/
+            return "";
```
Comment (MarcusGitty) [inline src/test/java/seedu/address/logic/commands/AddCommandTest.java:172]: Would returning a integer be better here ? this is to mirror the original model behavior

**Review by MarcusGitty — APPROVED** [review]
LGTM
