### PR TITLE
Fix editcommand tests

### LINKED ISSUE #56: EditCommand 6 Test Cases failing in EditCommandTest.java
Currently these 6 test are failing in EditCommandTest.java

image

### PR DESCRIPTION
**Pull request by jessicawyz**
Fix the test that are related to edit command

This one has checkstyle errors in test file typical person:

Static variable definition in wrong order. I can't seem to fix it after reordering attempts.

closes #56 

image

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -23,9 +24,11 @@
 import seedu.address.model.Model;
 import seedu.address.model.person.Address;
 import seedu.address.model.person.Email;
+import seedu.address.model.person.Id;
```
Comment (MarcusGitty) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:27]: Good catch !

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 2]
```diff
@@ -191,6 +210,20 @@ public void setAddress(Address address) {
...
+            return Optional.ofNullable(subject);
+        }
+
+        public void setId(Id uniqueID) {
+            this.uniqueID = uniqueID;
+        }
+
+        public Optional<Id> getId() {
+            return Optional.ofNullable(uniqueID);
+        }
```
Comment (MarcusGitty) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:226]: I like how you use the Optional class

File: src/test/java/seedu/address/testutil/TypicalPersons.java
Comment (MarcusGitty) [inline src/test/java/seedu/address/testutil/TypicalPersons.java:1]: I like how you formatted the typical persons, it looks good on the eyes !

**Review by MarcusGitty — APPROVED** [review]
LGTM !!

**Comment by MarcusGitty** [comment]
> Fix the test that are related to edit command
> 
> This one has checkstyle errors in test file typical person:
> 
> Static variable definition in wrong order. I can't seem to fix it after reordering attempts.
> 
> closes #56
> 
> image

Ooo the static order thingy, got some ordering as shown below de

image
